# Generated by Django 2.2.7 on 2020-01-02 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='todo',
            new_name='todom',
        ),
    ]
